name: build

on: 
  workflow_dispatch:
   
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up golang #安装python
      uses: actions/setup-go@v4
      with:
        go-version: 1.18
    - name: Get dependencies
        run: |
          go mod download
    - name: Build
        run: |
          go build -trimpath -ldflags \
          "-s -w -buildid= \
          -X 'github.com/indes/flowerss-bot/internal/config.commit=$(COMMIT)' \
          -X 'github.com/indes/flowerss-bot/internal/config.date=$(DATA)' \
          -X 'github.com/indes/flowerss-bot/internal/config.version=$(VERSION)'" -o $(app_name)
