name: Build & Deploy
on: [workflow_dispatch]
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:

        - name: Set up Go 1.18
        uses: actions/setup-go@v4
        with:
            go-version: 1.18
        id: go
        
        - name: check
        uses: actions/checkout@v3
        
        - name: Get dependencies
        run: |
          go mod download
          
        - name: Build
        run: |
          go build -trimpath -ldflags \
          "-s -w -buildid= \
          -X 'github.com/indes/flowerss-bot/internal/config.commit=$(COMMIT)' \
          -X 'github.com/indes/flowerss-bot/internal/config.date=$(DATA)' \
          -X 'github.com/indes/flowerss-bot/internal/config.version=$(VERSION)'" -o $(app_name)
          
        - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
            name: drone_test
            path: /home/runner/work/flowerss-bot/flowerss-bot
